default_install_hook_types: [pre-commit]
default_stages: [pre-commit]

repos:
  - repo: https://github.com/astral-sh/uv-pre-commit
    rev: 0.5.4
    hooks:
      - id: uv-lock
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.7.1
    hooks:
      - id: ruff
        args: [ --fix ]
      - id: ruff-format
  - repo: https://github.com/astral-sh/uv-pre-commit
    rev: 0.5.4
    hooks:
      - id: pip-compile
        args: [pyproject.toml, -o, requirements.txt]
        files: ^pyproject\.toml$
  - repo: local
    hooks:
      - id: pytest
        name: pytest
        entry: bash -c 'source .env && ./.venv/bin/pytest dagster_proj_tests/test_definitions.py'
        language: system
        pass_filenames: false
        always_run: true
  