dbt_strava:
  target: dev
  outputs:
    dev:
      type: duckdb
      path: '../{{ env_var("DUCKDB_DATABASE", "data/staging/strava.duckdb") }}'
    local:
      type: duckdb
      path: '../data/staging/strava.duckdb'
