dbt_strava:
  target: dev
  outputs:
    dev:
      type: duckdb
      schema: dbt
      path: '../{{ env_var("DUCKDB_DATABASE", "data/dev/strava.duckdb") }}'
    branch:
      account: '{{ env_var("DESTINATION__SNOWFLAKE__CREDENTIALS__HOST") }}'
      database: ANALYTICS_STG_DB
      password: '{{ env_var("DESTINATION__SNOWFLAKE__CREDENTIALS__PASSWORD") }}'
      role: DATA_ENGINEER
      schema: dbt
      threads: 4
      type: snowflake
      user: JAIRUSM
      warehouse: ANALYTICS_WH
    prod:
      account: '{{ env_var("DESTINATION__SNOWFLAKE__CREDENTIALS__HOST") }}'
      database: ANALYTICS_DB
      password: '{{ env_var("DESTINATION__SNOWFLAKE__CREDENTIALS__PASSWORD") }}'
      role: DATA_ENGINEER
      schema: dbt
      threads: 4
      type: snowflake
      user: JAIRUSM
      warehouse: ANALYTICS_WH
      