dbt_strava:
  target: dev
  outputs:
    dev:
      type: duckdb
      path: '../{{ env_var("DUCKDB_DATABASE", "data/dev/strava.duckdb") }}'
    branch:
      type: duckdb
      path: '../{{ env_var("DUCKDB_DATABASE", "data/branch/strava.duckdb") }}'
    prod:
      type: duckdb
      path: '../{{ env_var("DUCKDB_DATABASE", "data/prod/strava.duckdb") }}'
      